# Cloudflare Pages Configuration

name = "wayne-leighton"

# Cloudflare Pages specific configuration
[build]
command = "npm run build"
publish = "dist"
output_directory = "dist"
pages_build_output_dir = "dist"

[build.environment]
NODE_VERSION = "18"

# Environment variables needed for TinaCMS
[vars]
NEXT_PUBLIC_TINA_CLIENT_ID = "56844d01-3e31-4c3c-b165-956a1f1e0198"
TINA_TOKEN = "7a0024bf17443a12d8bf5054e078bd42af60c5e0"
TINA_PUBLIC_IS_LOCAL = "false"
GITHUB_OWNER = "CLAYYO"
GITHUB_REPO = "wayne-leighton"
GITHUB_BRANCH = "main"
GITHUB_PERSONAL_ACCESS_TOKEN = "7a0024bf17443a12d8bf5054e078bd42af60c5e0"

# Also include in environment-specific section
[env.production.vars]
NEXT_PUBLIC_TINA_CLIENT_ID = "56844d01-3e31-4c3c-b165-956a1f1e0198"
TINA_TOKEN = "7a0024bf17443a12d8bf5054e078bd42af60c5e0"
TINA_PUBLIC_IS_LOCAL = "false"
GITHUB_OWNER = "CLAYYO"
GITHUB_REPO = "wayne-leighton"
GITHUB_BRANCH = "main"
GITHUB_PERSONAL_ACCESS_TOKEN = "7a0024bf17443a12d8bf5054e078bd42af60c5e0"