backend:
  name: github
  repo: nickroberts/Wayne-Leighton-Books
  branch: main
  auth_type: implicit
  app_id: Ov23lio8ysSo7SIjtUEJ

media_folder: "public/images/books"
public_folder: "/images/books"

collections:
  - name: "books"
    label: "Books"
    folder: "src/content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Wayne Leighton"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Digital Price", name: "priceDigital", widget: "number", value_type: "float", step: 0.01}
      - {label: "Print Price", name: "pricePrint", widget: "number", value_type: "float", step: 0.01}
      - {label: "Cover Image", name: "coverImageUrl", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Leadership", "Business", "Marketing", "Personal Development"]}
      - {label: "Published Year", name: "publishedYear", widget: "number", value_type: "int"}
      - {label: "Pages", name: "pages", widget: "number", value_type: "int"}
      - {label: "ISBN", name: "isbn", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}